# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stefan/Dokumente/roleplays

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stefan/Dokumente/roleplays

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stefan/Dokumente/roleplays/CMakeFiles /home/stefan/Dokumente/roleplays/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stefan/Dokumente/roleplays/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TestFunctions

# Build rule for target.
TestFunctions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestFunctions
.PHONY : TestFunctions

# fast build rule for target.
TestFunctions/fast:
	$(MAKE) -f src/CMakeFiles/TestFunctions.dir/build.make src/CMakeFiles/TestFunctions.dir/build
.PHONY : TestFunctions/fast

#=============================================================================
# Target rules for targets named TermUtils

# Build rule for target.
TermUtils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TermUtils
.PHONY : TermUtils

# fast build rule for target.
TermUtils/fast:
	$(MAKE) -f src/CMakeFiles/TermUtils.dir/build.make src/CMakeFiles/TermUtils.dir/build
.PHONY : TermUtils/fast

#=============================================================================
# Target rules for targets named TextUtils

# Build rule for target.
TextUtils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TextUtils
.PHONY : TextUtils

# fast build rule for target.
TextUtils/fast:
	$(MAKE) -f src/CMakeFiles/TextUtils.dir/build.make src/CMakeFiles/TextUtils.dir/build
.PHONY : TextUtils/fast

#=============================================================================
# Target rules for targets named AdvLexer

# Build rule for target.
AdvLexer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AdvLexer
.PHONY : AdvLexer

# fast build rule for target.
AdvLexer/fast:
	$(MAKE) -f src/CMakeFiles/AdvLexer.dir/build.make src/CMakeFiles/AdvLexer.dir/build
.PHONY : AdvLexer/fast

#=============================================================================
# Target rules for targets named FileUtils

# Build rule for target.
FileUtils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FileUtils
.PHONY : FileUtils

# fast build rule for target.
FileUtils/fast:
	$(MAKE) -f src/CMakeFiles/FileUtils.dir/build.make src/CMakeFiles/FileUtils.dir/build
.PHONY : FileUtils/fast

#=============================================================================
# Target rules for targets named apiTest

# Build rule for target.
apiTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apiTest
.PHONY : apiTest

# fast build rule for target.
apiTest/fast:
	$(MAKE) -f src/CMakeFiles/apiTest.dir/build.make src/CMakeFiles/apiTest.dir/build
.PHONY : apiTest/fast

#=============================================================================
# Target rules for targets named rolePlayer

# Build rule for target.
rolePlayer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rolePlayer
.PHONY : rolePlayer

# fast build rule for target.
rolePlayer/fast:
	$(MAKE) -f src/CMakeFiles/rolePlayer.dir/build.make src/CMakeFiles/rolePlayer.dir/build
.PHONY : rolePlayer/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TestFunctions"
	@echo "... TermUtils"
	@echo "... TextUtils"
	@echo "... AdvLexer"
	@echo "... FileUtils"
	@echo "... apiTest"
	@echo "... rolePlayer"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

